Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from eli5.sklearn import explain_linear_regressor_weights

explain_linear_regressor_weights(
    # the classifier
    tfidf_clf,
    # the vectorizer that was used to transform the text
    vec=tfidf_vectorizer,
    # how many features to show in both the positive and negative directions
    # i.e. show the top 10 features that positively affect a classification decision in-favor of this label
    # and show the top 10 features that negatively affect a classification decision against this label
    top=(10, 10),
    # the "labels"
    target_names=tfidf_clf.classes_,
    # the feature names (in this case, the actual words)
    feature_names=tfidf_vectorizer.get_feature_names_out(),
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01meli5[39;00m[38;5;21;01m.[39;00m[38;5;21;01msklearn[39;00m [38;5;28;01mimport[39;00m explain_linear_regressor_weights
[1;32m      3[0m explain_linear_regressor_weights(
[1;32m      4[0m     [38;5;66;03m# the classifier[39;00m
[1;32m      5[0m     tfidf_clf,
[0;32m   (...)[0m
[1;32m     15[0m     feature_names[38;5;241m=[39mtfidf_vectorizer[38;5;241m.[39mget_feature_names_out(),
[1;32m     16[0m )

[0;31mModuleNotFoundError[0m: No module named 'eli5'

